"""Initial migration

Revision ID: 51de75122a09
Revises: 
Create Date: 2025-05-19 15:59:24.284072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51de75122a09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=94), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createdate', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=1023), nullable=False),
    sa.Column('back', sa.String(length=1023), nullable=False),
    sa.Column('indicator', sa.Boolean(), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['Sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cards')
    op.drop_table('Sets')
    op.drop_table('Users')
    # ### end Alembic commands ###
